modLoader = "javafml"
loaderVersion = "[46,)"
license = "MIT"
issueTrackerURL = "https://github.com/SteveKunG/FishOfThieves/issues"

[[mods]]
modId = "fishofthieves"
version = "${version}"
displayName = "Fish of Thieves"
description = "A mod adds all the fish from Sea of Thieves, fish fer ye pirate!"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/fish-of-thieves"
updateJSONURL = "https://raw.githubusercontent.com/SteveKunG/VersionCheckLibrary/master/fish_of_thieves.json"
logoFile = "logo.png"
authors = "SteveKunG, PloyiinGz"

[[dependencies.fishofthieves]]
modId = "forge"
mandatory = true
versionRange = "[46.0.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.fishofthieves]]
modId = "cloth_config"
mandatory = true
versionRange = "[11.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.fishofthieves]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.fishofthieves]]
modId = "aquaculture"
mandatory = false
versionRange = "[1.19.4-2.4.10,)"
ordering = "NONE"
side = "BOTH"