apply from: "https://raw.githubusercontent.com/SteveKunG/GradleScripts/main/architectury/fabric.gradle"

sourceSets {
    gametest {
        runtimeClasspath += main.runtimeClasspath + main.output
        compileClasspath += main.compileClasspath + main.output
    }
}

loom {
    runs.configureEach {
        properties project.commonProperties
        vmArgs project.commonVmArgs
        vmArgs project.hotswapVmArgs
    }

    mixin {
        useLegacyMixinAp = true
    }

    runs {
        client {
            if (project.hasProperty("usernameAndUUID")) {
                programArgs project.usernameAndUUID
            }
        }
        clientTerrablender {
            client()
            if (project.hasProperty("usernameAndUUID")) {
                programArgs project.usernameAndUUID
            }
            programArgs "--quickPlaySingleplayer", "TerraBlender"
        }
        gametest {
            if (project.hasProperty("usernameAndUUID")) {
                programArgs project.usernameAndUUID
            }
            client()
            name "Game Test Client"
            source sourceSets.gametest
            vmArg "-Dfabric-api.gametest"
        }
        datagen {
            server()
            name "Fabric Data Generation"
            property "fabric-api.datagen"
            property "fabric-api.datagen.strict-validation"
            property "fabric-api.datagen.output-dir", "${project(":common").file("src/generated/resources")}"
            runDir "build/datagen"
        }
    }
}

repositories {
    maven {
        name = "Fabric ASM"
        url = "https://jitpack.io/"
        content {
            includeGroup "com.github.Chocohead"
        }
    }
}

dependencies {
    modRuntimeOnly "maven.modrinth:continuity:${continuity_version}"
    modRuntimeOnly "maven.modrinth:cyanide:${cyanide_fabric_version}"
    modRuntimeOnly "maven.modrinth:xaeros-minimap:${xaeros_minimap_version}"
    modImplementation("com.github.glitchfiend:TerraBlender-fabric:${minecraft_version}-${terrablender_version}") {
        exclude group: "net.fabricmc.fabric-api"
        exclude group: "net.fabricmc", module: "fabric-loader"
    }
    modImplementation("com.github.glitchfiend:SereneSeasons-fabric:${minecraft_version}-${serene_seasons_version}")
    modRuntimeOnly "curse.maven:structure-void-toggle-357304:4736611"
    modImplementation(include("com.github.Chocohead:Fabric-ASM:v2.3"))
}

String fileName = "${archives_base_name}-mc${minecraft_version}"
List<String> devExcludes = ["**/gametest/", "**/datagen/", "data/forge/**", "*.snbt", "architectury.common.json"]

shadowJar {
    configurations = [project.configurations.shadowBundle]
    archiveClassifier = "dev"
    archiveVersion = "v${mod_version}"
    archiveBaseName = fileName
    excludes = devExcludes
}

sourcesJar {
    Jar commonSources = project(":common").sourcesJar
    dependsOn commonSources
    from commonSources.archiveFile.map { zipTree(it) }
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    excludes = devExcludes
}

tasks.register("apiJar", Jar) {
    group = "build"
    from project(":common").sourceSets.main.allJava
    from project(":common").sourceSets.main.output
    include "com/stevekung/fishofthieves/api/**/*"
    archiveVersion = "v${mod_version}"
    archiveBaseName = fileName
    archiveClassifier = "api"
}

assemble.dependsOn(apiJar)

remapSourcesJar {
    archiveVersion = "v${mod_version}"
    archiveBaseName = fileName
}

remapJar {
    injectAccessWidener = true
    inputFile.set shadowJar.archiveFile
    dependsOn shadowJar
    archiveClassifier = "fabric" + (release_type != "release" ? "-${release_type}" : "")
    archiveVersion = "v${mod_version}"
    archiveBaseName = fileName
}