apply from: "https://raw.githubusercontent.com/SteveKunG/GradleScripts/refs/heads/v2/architectury/fabric.gradle"

sourceSets {
    gametest {
        runtimeClasspath += main.runtimeClasspath + main.output
        compileClasspath += main.compileClasspath + main.output
    }
}

loom {
    runs.configureEach {
        systemProperties.putAll(rootProject.commonProperties)
        jvmArguments.addAll(rootProject.commonVmArgs)
        jvmArguments.addAll(rootProject.hotswapVmArgs)
    }

    runs {
        client {
            if (project.hasProperty("usernameAndUUID")) {
                programArguments.addAll(rootProject.usernameAndUUID)
            }
        }
        clientTerrablender {
            client()
            if (project.hasProperty("usernameAndUUID")) {
                programArguments.addAll(rootProject.usernameAndUUID)
            }
            programArguments.add("--quickPlaySingleplayer TerraBlender")
        }
        server {
            jvmArguments.add("-Dfabric-tag-conventions-v2.missingTagTranslationWarning=VERBOSE")
        }
        gametest {
            if (project.hasProperty("usernameAndUUID")) {
                programArguments.addAll(rootProject.usernameAndUUID)
            }
            client()
            displayName.set("Game Test Client")
            sourceSet.set("gametest")
            jvmArguments.add("-Dfabric-api.gametest")
        }
        datagen {
            server()
            displayName.set("Fabric Data Generation")
            systemProperties.put("fabric-api.datagen", "")
            systemProperties.put("fabric-api.datagen.strict-validation", "")
            systemProperties.put("fabric-api.datagen.output-dir", "${project(":common").file("src/generated/resources")}")
            runDirectory.set("build/datagen")
        }
        datagenClient {
            client()
            displayName.set("Fabric Data Generation Client")
            systemProperties.put("fabric-api.datagen", "")
            systemProperties.put("fabric-api.datagen.strict-validation", "")
            systemProperties.put("fabric-api.datagen.output-dir", "${project(":common").file("src/generated/resources")}")
            runDirectory.set("build/datagen")
        }
    }
}

repositories {
    maven {
        url = "https://chocolateminecraft.com/maven"
        name = "Xaero's Maven"
    }
}

dependencies {
    localRuntime "maven.modrinth:continuity:${continuity_version}"
    localRuntime "maven.modrinth:xaeros-minimap:fabric-${xaeros_minimap_version}"
    localRuntime "xaero.lib:xaerolib-fabric-${minecraft_version}:+"
    implementation("com.github.glitchfiend:TerraBlender-fabric:${minecraft_version}-${terrablender_version}") {
        exclude group: "net.fabricmc.fabric-api"
        exclude group: "net.fabricmc", module: "fabric-loader"
    }
    compileOnly("com.github.glitchfiend:SereneSeasons-fabric:${minecraft_version}-${serene_seasons_version}")
    localRuntime "maven.modrinth:structure-void-toggle:4.5.4+26.1"
}

processResources {
    delete {
        delete "${projectDir}/src/main/resources/resourcepacks/simple_spawning_condition_pack"
    }
    copy {
        from("../common/src/generated/resources/resourcepacks")
        into("$projectDir/src/main/resources/resourcepacks")
    }
}

List<String> devExcludes = ["**/gametest/", "**/datagen/", "data/forge/**", "gametest_structures/**", "regular_structures/**", "architectury.common.json"]

jar {
    archiveClassifier = "raw"
    archiveVersion = "v${mod_version}"
    archiveBaseName = project(":common").ext.fileName
    excludes = devExcludes
}

shadowJar {
    dependsOn jar
    mainSpec.sourcePaths.clear()       // Remove default source set inclusion
    from zipTree(jar.archiveFile)     // Unpack jar output (preserves Loom modifications)

    configurations = [project.configurations.shadowBundle]
    archiveClassifier = "fabric" + (release_type != "release" ? "-${release_type}" : "")
    archiveVersion = "v${mod_version}"
    archiveBaseName = project(":common").ext.fileName
}

sourcesJar {
    Jar commonSources = project(":common").sourcesJar
    dependsOn commonSources
    from commonSources.archiveFile.map { zipTree(it) }
    archiveVersion = "v${mod_version}"
    archiveBaseName = project(":common").ext.fileName
    excludes = devExcludes
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

tasks.register("apiJar", Jar) {
    group = "build"
    from project(":common").sourceSets.main.allJava
    from project(":common").sourceSets.main.output
    include "com/stevekung/fishofthieves/api/**/*"
    archiveVersion = "v${mod_version}"
    archiveBaseName = project(":common").ext.fileName
    archiveClassifier = "api"
}

assemble.dependsOn(apiJar)

processGametestResources {
    File sourceDir = project(":fabric").file("src/gametest/resources/data/minecraft/gametest/structure")
    File destinationDir = project(":fabric").file("run/gameteststructures")

    if (!destinationDir.exists()) {
        destinationDir.mkdirs()
    }

    sourceDir.eachFileRecurse { File file ->
        if (file.isFile()) {
            File targetFile = new File(destinationDir, sourceDir.toPath().relativize(file.toPath()).toString())

            file.withInputStream { input ->
                targetFile.withOutputStream { output ->
                    output << input
                }
            }
        }
    }
}