# gradle
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
java_version=21
use_datagen=true
use_mixin=true
use_access_widener=true
upload_debug=true
loom.ignoreDependencyLoomVersionValidation=true

# minecraft
minecraft_version=1.21.11
parchmentmc_version=1.21.11:2025.12.20

# mod
display_name=Fish of Thieves
archives_base_name=fish_of_thieves
mod_id=fishofthieves
mod_description=A mod adds all the fish from the Sea of Thieves, fish fer ye pirate!
maven_group=com.stevekung.fishofthieves
mod_version=21.11.0.3
release_type=release
enabled_platforms=fabric,neoforge
cloth_config_version=21.11.151
terrablender_version=1.21.11-21.11.0.0
serene_seasons_version=1.21.11-21.11.0.0
glitchcore_version=1.21.11-21.11.0.2
xaeros_minimap_version=fabric-1.21.11-25.3.5

# curseforge
curseforge_project_id=568372
curseforge_fabric_required_dependencies=fabric-api,cloth-config
curseforge_fabric_optional_dependencies=modmenu,continuity,fishing-real,terrablender-fabric
curseforge_neoforge_required_dependencies=cloth-config
curseforge_neoforge_optional_dependencies=configured,fishing-real,terrablender-neoforge,aquaculture

# modrinth
modrinth_project_id=fish-of-thieves
modrinth_fabric_required_dependencies=fabric-api,cloth-config
modrinth_fabric_optional_dependencies=modmenu,continuity,fishing-real,terrablender
modrinth_neoforge_required_dependencies=cloth-config
modrinth_neoforge_optional_dependencies=fishing-real,terrablender,aquaculture

# fabric
fabric_loader_version=0.18.4
fabric_api_version=0.141.1+1.21.11
modmenu_version=17.0.0-beta.2
continuity_version=3.0.1-beta.1+1.21.11

# neoforge
neoforge_version=21.11.27-beta
aquaculture_version=1.21.11:1.21.11-2.8.4
mixin_constraints_version=1.1.0