# gradle
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
java_version=17
use_datagen=true
use_mixin=true
use_access_widener=true
upload_debug=true

# minecraft
minecraft_version=1.20.1
parchmentmc_version=1.20.1:2023.09.03

# mod
display_name=Fish of Thieves
archives_base_name=fish_of_thieves
mod_id=fishofthieves
mod_description=A mod adds all the fish from the Sea of Thieves, fish fer ye pirate!
maven_group=com.stevekung.fishofthieves
mod_version=3.1.4
release_type=release
enabled_platforms=fabric,forge
cloth_config_version=11.1.118
terrablender_version=3.0.1.7

# curseforge
curseforge_project_id=568372
curseforge_fabric_required_dependencies=fabric-api,cloth-config
curseforge_fabric_optional_dependencies=modmenu,continuity,fishing-real,terrablender-fabric
curseforge_forge_required_dependencies=cloth-config
curseforge_forge_optional_dependencies=configured,fishing-real,terrablender

# modrinth
modrinth_project_id=fish-of-thieves
modrinth_fabric_required_dependencies=fabric-api,cloth-config
modrinth_fabric_optional_dependencies=modmenu,continuity,fishing-real,terrablender
modrinth_forge_required_dependencies=cloth-config
modrinth_forge_optional_dependencies=fishing-real,terrablender

# fabric
fabric_loader_version=0.17.2
fabric_api_version=0.92.6+1.20.1
modmenu_version=7.2.2
continuity_version=3.0.0-beta.5+1.20.1
cyanide_fabric_version=XqTNiiKd

# forge
forge_version=47.4.9
aquaculture_version=1.19.4-2.4.17
mixinextras_version=0.5.0
cyanide_forge_version=4.1.1