# gradle
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
java_version=21
use_datagen=true
use_mixin=true
use_access_widener=true
upload_debug=true
loom.ignoreDependencyLoomVersionValidation=true

# minecraft
minecraft_version=25w37a
parchmentmc_version=1.21.8:2025.07.20

# mod
display_name=Fish of Thieves
archives_base_name=fish_of_thieves
mod_id=fishofthieves
mod_description=A mod adds all the fish from the Sea of Thieves, fish fer ye pirate!
maven_group=com.stevekung.fishofthieves
mod_version=4.1.3
release_type=release
enabled_platforms=fabric
cloth_config_version=19.0.147
terrablender_version=1.21.8-6.0.0.3

# curseforge
curseforge_project_id=568372
curseforge_fabric_required_dependencies=fabric-api,cloth-config
curseforge_fabric_optional_dependencies=modmenu,continuity,fishing-real,terrablender-fabric
curseforge_neoforge_required_dependencies=cloth-config
curseforge_neoforge_optional_dependencies=configured,fishing-real,terrablender-neoforge

# modrinth
modrinth_project_id=fish-of-thieves
modrinth_fabric_required_dependencies=fabric-api,cloth-config
modrinth_fabric_optional_dependencies=modmenu,continuity,fishing-real,terrablender
modrinth_neoforge_required_dependencies=cloth-config
modrinth_neoforge_optional_dependencies=fishing-real,terrablender

# fabric
fabric_loader_version=0.17.2
fabric_api_version=0.133.6+1.21.9
#modmenu_version=15.0.0-beta.3 TODO
continuity_version=3.0.1-beta.1+1.21.6

# neoforge
neoforge_version=21.8.13
aquaculture_version=1.21.5:1.21.5-2.8.2