package com.stevekung.fishofthieves.references;

import com.stevekung.fishofthieves.FishOfThieves;

import net.minecraft.references.BlockItemId;

public class FOTBlockItemIds
{
    public static final BlockItemId FISH_BONE = create("fish_bone");
    public static final BlockItemId SHOAL = create("shoal");
    public static final BlockItemId OAK_FISH_PLAQUE = create("oak_fish_plaque");
    public static final BlockItemId SPRUCE_FISH_PLAQUE = create("spruce_fish_plaque");
    public static final BlockItemId BIRCH_FISH_PLAQUE = create("birch_fish_plaque");
    public static final BlockItemId JUNGLE_FISH_PLAQUE = create("jungle_fish_plaque");
    public static final BlockItemId ACACIA_FISH_PLAQUE = create("acacia_fish_plaque");
    public static final BlockItemId DARK_OAK_FISH_PLAQUE = create("dark_oak_fish_plaque");
    public static final BlockItemId MANGROVE_FISH_PLAQUE = create("mangrove_fish_plaque");
    public static final BlockItemId CHERRY_FISH_PLAQUE = create("cherry_fish_plaque");
    public static final BlockItemId PALE_OAK_FISH_PLAQUE = create("pale_oak_fish_plaque");
    public static final BlockItemId BAMBOO_FISH_PLAQUE = create("bamboo_fish_plaque");
    public static final BlockItemId CRIMSON_FISH_PLAQUE = create("crimson_fish_plaque");
    public static final BlockItemId WARPED_FISH_PLAQUE = create("warped_fish_plaque");
    public static final BlockItemId IRON_FRAME_OAK_FISH_PLAQUE = create("iron_frame_oak_fish_plaque");
    public static final BlockItemId IRON_FRAME_SPRUCE_FISH_PLAQUE = create("iron_frame_spruce_fish_plaque");
    public static final BlockItemId IRON_FRAME_BIRCH_FISH_PLAQUE = create("iron_frame_birch_fish_plaque");
    public static final BlockItemId IRON_FRAME_JUNGLE_FISH_PLAQUE = create("iron_frame_jungle_fish_plaque");
    public static final BlockItemId IRON_FRAME_ACACIA_FISH_PLAQUE = create("iron_frame_acacia_fish_plaque");
    public static final BlockItemId IRON_FRAME_DARK_OAK_FISH_PLAQUE = create("iron_frame_dark_oak_fish_plaque");
    public static final BlockItemId IRON_FRAME_MANGROVE_FISH_PLAQUE = create("iron_frame_mangrove_fish_plaque");
    public static final BlockItemId IRON_FRAME_CHERRY_FISH_PLAQUE = create("iron_frame_cherry_fish_plaque");
    public static final BlockItemId IRON_FRAME_PALE_OAK_FISH_PLAQUE = create("iron_frame_pale_oak_fish_plaque");
    public static final BlockItemId IRON_FRAME_BAMBOO_FISH_PLAQUE = create("iron_frame_bamboo_fish_plaque");
    public static final BlockItemId IRON_FRAME_CRIMSON_FISH_PLAQUE = create("iron_frame_crimson_fish_plaque");
    public static final BlockItemId IRON_FRAME_WARPED_FISH_PLAQUE = create("iron_frame_warped_fish_plaque");
    public static final BlockItemId GOLDEN_FRAME_OAK_FISH_PLAQUE = create("golden_frame_oak_fish_plaque");
    public static final BlockItemId GOLDEN_FRAME_SPRUCE_FISH_PLAQUE = create("golden_frame_spruce_fish_plaque");
    public static final BlockItemId GOLDEN_FRAME_BIRCH_FISH_PLAQUE = create("golden_frame_birch_fish_plaque");
    public static final BlockItemId GOLDEN_FRAME_JUNGLE_FISH_PLAQUE = create("golden_frame_jungle_fish_plaque");
    public static final BlockItemId GOLDEN_FRAME_ACACIA_FISH_PLAQUE = create("golden_frame_acacia_fish_plaque");
    public static final BlockItemId GOLDEN_FRAME_DARK_OAK_FISH_PLAQUE = create("golden_frame_dark_oak_fish_plaque");
    public static final BlockItemId GOLDEN_FRAME_MANGROVE_FISH_PLAQUE = create("golden_frame_mangrove_fish_plaque");
    public static final BlockItemId GOLDEN_FRAME_CHERRY_FISH_PLAQUE = create("golden_frame_cherry_fish_plaque");
    public static final BlockItemId GOLDEN_FRAME_PALE_OAK_FISH_PLAQUE = create("golden_frame_pale_oak_fish_plaque");
    public static final BlockItemId GOLDEN_FRAME_BAMBOO_FISH_PLAQUE = create("golden_frame_bamboo_fish_plaque");
    public static final BlockItemId GOLDEN_FRAME_CRIMSON_FISH_PLAQUE = create("golden_frame_crimson_fish_plaque");
    public static final BlockItemId GOLDEN_FRAME_WARPED_FISH_PLAQUE = create("golden_frame_warped_fish_plaque");
    public static final BlockItemId COPPER_FRAME_OAK_FISH_PLAQUE = create("copper_frame_oak_fish_plaque");
    public static final BlockItemId COPPER_FRAME_SPRUCE_FISH_PLAQUE = create("copper_frame_spruce_fish_plaque");
    public static final BlockItemId COPPER_FRAME_BIRCH_FISH_PLAQUE = create("copper_frame_birch_fish_plaque");
    public static final BlockItemId COPPER_FRAME_JUNGLE_FISH_PLAQUE = create("copper_frame_jungle_fish_plaque");
    public static final BlockItemId COPPER_FRAME_ACACIA_FISH_PLAQUE = create("copper_frame_acacia_fish_plaque");
    public static final BlockItemId COPPER_FRAME_DARK_OAK_FISH_PLAQUE = create("copper_frame_dark_oak_fish_plaque");
    public static final BlockItemId COPPER_FRAME_MANGROVE_FISH_PLAQUE = create("copper_frame_mangrove_fish_plaque");
    public static final BlockItemId COPPER_FRAME_CHERRY_FISH_PLAQUE = create("copper_frame_cherry_fish_plaque");
    public static final BlockItemId COPPER_FRAME_PALE_OAK_FISH_PLAQUE = create("copper_frame_pale_oak_fish_plaque");
    public static final BlockItemId COPPER_FRAME_BAMBOO_FISH_PLAQUE = create("copper_frame_bamboo_fish_plaque");
    public static final BlockItemId COPPER_FRAME_CRIMSON_FISH_PLAQUE = create("copper_frame_crimson_fish_plaque");
    public static final BlockItemId COPPER_FRAME_WARPED_FISH_PLAQUE = create("copper_frame_warped_fish_plaque");
    public static final BlockItemId GILDED_OAK_FISH_PLAQUE = create("gilded_oak_fish_plaque");
    public static final BlockItemId GILDED_SPRUCE_FISH_PLAQUE = create("gilded_spruce_fish_plaque");
    public static final BlockItemId GILDED_BIRCH_FISH_PLAQUE = create("gilded_birch_fish_plaque");
    public static final BlockItemId GILDED_JUNGLE_FISH_PLAQUE = create("gilded_jungle_fish_plaque");
    public static final BlockItemId GILDED_ACACIA_FISH_PLAQUE = create("gilded_acacia_fish_plaque");
    public static final BlockItemId GILDED_DARK_OAK_FISH_PLAQUE = create("gilded_dark_oak_fish_plaque");
    public static final BlockItemId GILDED_MANGROVE_FISH_PLAQUE = create("gilded_mangrove_fish_plaque");
    public static final BlockItemId GILDED_CHERRY_FISH_PLAQUE = create("gilded_cherry_fish_plaque");
    public static final BlockItemId GILDED_PALE_OAK_FISH_PLAQUE = create("gilded_pale_oak_fish_plaque");
    public static final BlockItemId GILDED_BAMBOO_FISH_PLAQUE = create("gilded_bamboo_fish_plaque");
    public static final BlockItemId GILDED_CRIMSON_FISH_PLAQUE = create("gilded_crimson_fish_plaque");
    public static final BlockItemId GILDED_WARPED_FISH_PLAQUE = create("gilded_warped_fish_plaque");
    public static final BlockItemId SMALL_COCONUT_LOG = create("small_coconut_log");
    public static final BlockItemId COCONUT_FRUIT_GROWABLE_LOG = create("coconut_fruit_growable_log");
    public static final BlockItemId SMALL_TOP_COCONUT_LOG = create("small_top_coconut_log");
    public static final BlockItemId SMALL_COCONUT_WOOD = create("small_coconut_wood");
    public static final BlockItemId MEDIUM_COCONUT_LOG = create("medium_coconut_log");
    public static final BlockItemId MEDIUM_COCONUT_WOOD = create("medium_coconut_wood");
    public static final BlockItemId COCONUT_LOG = create("coconut_log");
    public static final BlockItemId COCONUT_WOOD = create("coconut_wood");
    public static final BlockItemId STRIPPED_COCONUT_LOG = create("stripped_coconut_log");
    public static final BlockItemId STRIPPED_COCONUT_WOOD = create("stripped_coconut_wood");
    public static final BlockItemId STRIPPED_MEDIUM_COCONUT_LOG = create("stripped_medium_coconut_log");
    public static final BlockItemId STRIPPED_MEDIUM_COCONUT_WOOD = create("stripped_medium_coconut_wood");
    public static final BlockItemId STRIPPED_SMALL_COCONUT_LOG = create("stripped_small_coconut_log");
    public static final BlockItemId STRIPPED_SMALL_COCONUT_WOOD = create("stripped_small_coconut_wood");
    public static final BlockItemId COCONUT_SAPLING = create("coconut_sapling");
    public static final BlockItemId COCONUT_FRUIT = create("coconut_fruit");
    public static final BlockItemId COCONUT_FRONDS = create("coconut_fronds");
    public static final BlockItemId BANANA_STEM = create("banana_stem");
    public static final BlockItemId BANANA_CLUSTER_GROWABLE_STEM = create("banana_cluster_growable_stem");
    public static final BlockItemId BANANA_LEAVES = create("banana_leaves");
    public static final BlockItemId VERTICAL_BANANA_LEAVES = create("vertical_banana_leaves");
    public static final BlockItemId VERTICAL_COCONUT_FRONDS = create("vertical_coconut_fronds");
    public static final BlockItemId BANANA_SHOOTS = create("banana_shoots");
    public static final BlockItemId BANANA_SHOOTS_PLANT = create("banana_shoots_plant");
    public static final BlockItemId BANANA_BLOSSOM = create("banana_blossom");
    public static final BlockItemId BANANA_BLOSSOM_PLANT = create("banana_blossom_plant");
    public static final BlockItemId UNDERRIPE_BANANA_CLUSTER_PLANT = create("underripe_banana_cluster_plant");
    public static final BlockItemId BARELY_RIPE_BANANA_CLUSTER_PLANT = create("barely_ripe_banana_cluster_plant");
    public static final BlockItemId RIPE_BANANA_CLUSTER_PLANT = create("ripe_banana_cluster_plant");
    public static final BlockItemId UNDERRIPE_BANANA_CLUSTER = create("underripe_banana_cluster");
    public static final BlockItemId BARELY_RIPE_BANANA_CLUSTER = create("barely_ripe_banana_cluster");
    public static final BlockItemId RIPE_BANANA_CLUSTER = create("ripe_banana_cluster");
    public static final BlockItemId PINEAPPLE_CROP = create("pineapple_crop");
    public static final BlockItemId RIPE_PINEAPPLE_BLOCK = create("ripe_pineapple_block");
    public static final BlockItemId CROWNLESS_RIPE_PINEAPPLE_BLOCK = create("crownless_ripe_pineapple_block");
    public static final BlockItemId UNDERRIPE_PINEAPPLE_BLOCK = create("underripe_pineapple_block");
    public static final BlockItemId MANGO_LEAVES = create("mango_leaves");
    public static final BlockItemId MANGO_FRUIT = create("mango_fruit");
    public static final BlockItemId HANGING_MANGO_FRUIT = create("hanging_mango_fruit");
    public static final BlockItemId TALL_POMEGRANATE_PLANT = create("tall_pomegranate_plant");
    public static final BlockItemId PRISMARIZED_LOG = create("prismarized_log");
    public static final BlockItemId BUDDING_PRISMARIZED_LOG = create("budding_prismarized_log");
    public static final BlockItemId GUARDIAN_FRUIT = create("guardian_fruit");
    public static final BlockItemId PINK_PLUMERIA = create("pink_plumeria");
    public static final BlockItemId LIGHT_BLUE_PLUMERIA = create("light_blue_plumeria");
    public static final BlockItemId WHITE_PLUMERIA = create("white_plumeria");
    public static final BlockItemId MANGO_PIT = create("mango_pit");
    public static final BlockItemId MANGO_SAPLING = create("mango_sapling");
    public static final BlockItemId POMEGRANATE_PLANT = create("pomegranate_plant");
    public static final BlockItemId POMEGRANATE_SAPLING = create("pomegranate_sapling");
    public static final BlockItemId TROPICAL_RED_FERN = create("tropical_red_fern");
    public static final BlockItemId TROPICAL_MONSTERA = create("tropical_monstera");
    public static final BlockItemId COCONUT_PLANKS = create("coconut_planks");
    public static final BlockItemId COCONUT_BUTTON = create("coconut_button");
    public static final BlockItemId COCONUT_FENCE = create("coconut_fence");
    public static final BlockItemId COCONUT_FENCE_GATE = create("coconut_fence_gate");
    public static final BlockItemId COCONUT_PRESSURE_PLATE = create("coconut_pressure_plate");
    public static final BlockItemId COCONUT_SLAB = create("coconut_slab");
    public static final BlockItemId COCONUT_STAIRS = create("coconut_stairs");
    public static final BlockItemId COCONUT_TRAPDOOR = create("coconut_trapdoor");
    public static final BlockItemId COCONUT_DOOR = create("coconut_door");
    public static final BlockItemId COCONUT_SIGN = create("coconut_sign");
    public static final BlockItemId COCONUT_WALL_SIGN = create("coconut_wall_sign");
    public static final BlockItemId COCONUT_HANGING_SIGN = create("coconut_hanging_sign");
    public static final BlockItemId COCONUT_WALL_HANGING_SIGN = create("coconut_wall_hanging_sign");
    public static final BlockItemId COCONUT_FISH_PLAQUE = create("coconut_fish_plaque");
    public static final BlockItemId IRON_FRAME_COCONUT_FISH_PLAQUE = create("iron_frame_coconut_fish_plaque");
    public static final BlockItemId COPPER_FRAME_COCONUT_FISH_PLAQUE = create("copper_frame_coconut_fish_plaque");
    public static final BlockItemId GOLDEN_FRAME_COCONUT_FISH_PLAQUE = create("golden_frame_coconut_fish_plaque");
    public static final BlockItemId GILDED_COCONUT_FISH_PLAQUE = create("gilded_coconut_fish_plaque");
    public static final BlockItemId COCONUT_SHELF = create("coconut_shelf");

    public static BlockItemId create(String name)
    {
        var id = FishOfThieves.id(name);
        return BlockItemId.create(id, id);
    }
}