apply from: "https://raw.githubusercontent.com/SteveKunG/GradleScripts/refs/heads/v2/architectury/neoforge.gradle"

loom {
    runs.configureEach {
        systemProperties.putAll(rootProject.commonProperties)
        jvmArguments.addAll(rootProject.commonVmArgs)
        jvmArguments.addAll(rootProject.hotswapVmArgs)
    }

    runs {
        client {
            if (project.hasProperty("usernameAndUUID")) {
                programArguments.addAll(rootProject.usernameAndUUID)
            }
            displayName.set("Minecraft Client " + minecraft_version)
        }
        server {
            displayName.set("Minecraft Client " + minecraft_version)
        }
        data {
            serverData()
            programArguments.addAll("--mod=fishofthieves", "--all", "--output=" + file("src/generated/resources/"), "--existing=" + project(":common").file("src/main/resources/"))
            displayName.set("NeoForge Data Generation " + minecraft_version)
        }
    }
}

repositories {
    maven {
        name = "Aquaculture 2"
        url = "https://girafi.dk/maven/"
        content {
            includeGroup "com.teammetallurgy.aquaculture"
        }
    }
}

dependencies {
    api "com.teammetallurgy.aquaculture:aquaculture2_26.1.1:${aquaculture_version}:api"
    implementation "com.github.glitchfiend:TerraBlender-neoforge:${minecraft_version}-${terrablender_version}"
    compileOnly "com.github.glitchfiend:SereneSeasons-neoforge:${minecraft_version}-${serene_seasons_version}"
    implementation "com.github.glitchfiend:GlitchCore-neoforge:${minecraft_version}-${glitchcore_version}"
    implementation(include("com.moulberry:mixinconstraints:${mixin_constraints_version}"))
}

processResources {
    delete {
        delete "${projectDir}/src/main/resources/simple_spawning_condition_pack"
    }
    copy {
        from("../common/src/generated/resources/resourcepacks")
        into("$projectDir/src/main/resources")
    }
}

List<String> commonExcludes = [".cache", "**/datagen/", "**/resourcepacks/", "gametest_structures/**", "regular_structures/**", "data/fabric/**", "architectury.common.json"]

jar {
    archiveClassifier = "raw"
    archiveVersion = "v${mod_version}"
    archiveBaseName = project(":common").ext.fileName
    excludes = commonExcludes
}

shadowJar {
    dependsOn jar
    mainSpec.sourcePaths.clear()       // Remove default source set inclusion
    from zipTree(jar.archiveFile)     // Unpack jar output (preserves Loom modifications)

    configurations = [project.configurations.shadowBundle]
    archiveClassifier = "neoforge" + (release_type != "release" ? "-${release_type}" : "")
    archiveVersion = "v${mod_version}"
    archiveBaseName = project(":common").ext.fileName
}

sourcesJar {
    Jar commonSources = project(":common").sourcesJar
    dependsOn commonSources
    commonSources.exclude ".cache"
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    from commonSources.archiveFile.map { zipTree(it) }
    archiveVersion = "v${mod_version}"
    archiveBaseName = project(":common").ext.fileName
    excludes = commonExcludes
}

tasks.register("apiJar", Jar) {
    group = "build"
    from project(":common").sourceSets.main.allJava
    from project(":common").sourceSets.main.output
    include "com/stevekung/fishofthieves/api/**/*"
    archiveVersion = "v${mod_version}"
    archiveBaseName = project(":common").ext.fileName
    archiveClassifier = "api"
}

assemble.dependsOn(apiJar)